sudo: required
services:
  - docker

before_install:
  - ./scripts/build_test_images.sh

script:
  - ./scripts/run_tests.sh

after_success:
  - ./scripts/push_to_docker.sh

deploy:
  provider: script
  script: bash ./scripts/push_to_heroku.sh
  app: koel-recreation
  on: 
    branch: master
  api_key:
      secure: $HEROKU_SECRET_KEY